# Generated by Django 6.0 on 2026-01-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_routes_and_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='seats',
            field=models.IntegerField(blank=True),
        ),
    ]
